### ISSUE TITLE
Not detect IP Windows 10

### ISSUE THREAD

**Issue by lgcambero** [xchwarze/Cain#1]
Hello, when I will select the interface to work with me Cain detects all but as you see in the picture does not detect the IP address or Gateway. You have thought that he might be? Thank you.
![sin titulo](https://cloud.githubusercontent.com/assets/11602705/14232371/24a9c330-f980-11e5-9d97-9152c1d71b5e.jpg)

**Comment by xchwarze** [comment]
hello! this is a winpcap driver bug (maybe)
check with this drivers http://www.win10pcap.org/download/

**Comment by hsluoyz** [comment]
Hi.

You would like to try Npcap: https://github.com/nmap/npcap.

It's another fork of WinPcap with multiple new features.

**Comment by xchwarze** [comment]
1) Open adapter properties
2) Select Internet Protocol Version 4 (TCP/IPv4) and then select Properties.
3) Select "Advanced" and go to DNS Tab
4) Check "Use this connection's DNS suffix in DNS registration"

winpcap fix: https://www.youtube.com/watch?v=hf_UzCecyps
